---
deployment:
  tasks:
    - export DEPLOYPATH=/home/totclanc/public_html/
    - export DEPLOYIMAGEPATH=/home/totclanc/public_html/images
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp header.webp $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp smalerHeader.webp $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp siteError.html $DEPLOYPATH
    - /bin/cp siteError.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp Tot1ClanLogo.webp $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R images $DEPLOYIMAGEPATH