---
deployment:
  tasks:
    - export DEPLOYPATH=/home/totclanc/public_html/
    - export DEPLOYIMAGEPATH=/home/totclanc/public_html/images
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp hi-def.jpg $DEPLOYPATH
    - /bin/cp header.jpg $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp smalerHeader.jpg $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp siteError.html $DEPLOYPATH
    - /bin/cp siteError.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp android-chrome-192x192.png $DEPLOYPATH
    - /bin/cp android-chrome-512x512.png $DEPLOYPATH
    - /bin/cp apple-touch-icon.png $DEPLOYPATH
    - /bin/cp favicon-16x16.png $DEPLOYPATH
    - /bin/cp favicon-32x32.png $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R images $DEPLOYIMAGEPATH